### ISSUE TITLE
Item teleporter is bugged

### ISSUE THREAD

**Issue by 1lluminat1** [3Snake3/ADC#11]
I'm playing on mindustry version 140.4. The item teleporter seems to delete items when used at a higher throughput. It makes a schematic run at half efficiency bur when I replace the item teleporters with tiny mass drivers the schematic runs at 100% efficiency.

**Comment by 3Snake3** [comment]
> 

Teleporter is too buggy at the moment, I know that problem. I plan to introduce a brand new teleporter that performs its functions exactly.

**Comment by 3Snake3** [comment]
@1lluminat1 Teleporter has been fixed successfully
