### ISSUE TITLE
Garnet Extractor

### ISSUE THREAD

**Issue by Schwartz-Schwi** [3Snake3/ADC#12]
I've been playing this mod for weeks now but I still can't find the Garnet Extractor Icon I can't advance the mod research related to garnet on Erikin research because of this

**Comment by 3Snake3** [comment]
> I've been playing this mod for weeks now but I still can't find the Garnet Extractor Icon I can't advance the mod research related to garnet on Erikin research because of this

The content related to garnet is WIP(Work in progress) and cannot be fully playable yet.

**Comment by Schwartz-Schwi** [comment]
> > I've been playing this mod for weeks now but I still can't find the Garnet Extractor Icon I can't advance the mod research related to garnet on Erikin research because of this
> 
> The content related to garnet is WIP(Work in progress) and cannot be fully playable yet.

Ohhh I see, looking forward to the release of it:)

**Comment by 3Snake3** [comment]
> > > I've been playing this mod for weeks now but I still can't find the Garnet Extractor Icon I can't advance the mod research related to garnet on Erikin research because of this
> > 
> > The content related to garnet is WIP(Work in progress) and cannot be fully playable yet.
> 
> Ohhh I see, looking forward to the release of it:)

I'm afraid that you will need to start the campaign again after the update, as big changes are coming and this may have a bad effect on your progress.

**Comment by Schwartz-Schwi** [comment]
> > > > I've been playing this mod for weeks now but I still can't find the Garnet Extractor Icon I can't advance the mod research related to garnet on Erikin research because of this
> > > 
> > > 
> > > The content related to garnet is WIP(Work in progress) and cannot be fully playable yet.
> > 
> > 
> > Ohhh I see, looking forward to the release of it:)
> 
> I'm afraid that you will need to start the campaign again after the update, as big changes are coming and this may have a bad effect on your progress.

I don't really mind it, as a am just learning some method to play the game, and find new way too play it, but I really do hope find a mod that have a reliable power generation for Irekin, the new revelation mod and your mod helps me a lot to find new methods and breaking mechanics to play and break the game
