### ISSUE TITLE
Hydrogenerator not Working

### ISSUE THREAD

**Issue by Judykins** [3Snake3/ADC#13]
Hi, 

Updated today 11 February 2023.
Hydrogenerator no longer functioning on ice or snow.

By design or accidental? 
Cos I can't think of a wetter thing than snow/ice other than just water haha.

**Comment by 3Snake3** [comment]
> Hi, 
> 
> Updated today 11 February 2023.
> Hydrogenerator no longer functioning on ice or snow.
> 
> By design or accidental? 
> Cos I can't think of a wetter thing than snow/ice other than just water haha.

Hello!
Let me check it, I'll answer you about it later

**Comment by Judykins** [comment]
It was my own game, other mods clashed!

Specifically "Aeyama: the new world"

**Comment by 3Snake3** [comment]
> It was my own game, other mods clashed!
> 
> Specifically "Aeyama: the new world"

So everything is fine with the hydrogenerator?
