### ISSUE TITLE
corkscrew is currently op

### ISSUE THREAD

**Issue by kapzduke** [3Snake3/ADC#17]
https://user-images.githubusercontent.com/60543005/230341956-4f1ce88c-592f-4877-bcf6-0d37d4115695.mp4

**Comment by 3Snake3** [comment]
> 
> https://user-images.githubusercontent.com/60543005/230341956-4f1ce88c-592f-4877-bcf6-0d37d4115695.mp4
> 
> 

Content reworking on Erekir is planned for the next update.

**Comment by kapzduke** [comment]
is this your excuse to not balance it

**Comment by KOCTOLOM** [comment]
This update focus on serpulo. I know that erekir turrets havent balance (it will be in next update with full rework of erekir mod content)
