### ISSUE TITLE
Some Projectiles Have Oddly Short lifetime

### ISSUE THREAD

**Issue by Cry0flu1d** [3Snake3/ADC#22]
Such as Shriek's main bullet and Whirlpool's side cannon
![image](https://github.com/3Snake3/Sapphirium/assets/99197260/72813e9f-3c63-40f3-809e-aaab6382cbe0)
![image](https://github.com/3Snake3/Sapphirium/assets/99197260/c09949ef-589b-4dae-8716-f02c860cf8c3)
Is it intentially?

**Comment by 3Snake3** [comment]
> Such as Shriek's main bullet and Whirlpool's side cannon
> ![image](https://github.com/3Snake3/Sapphirium/assets/99197260/72813e9f-3c63-40f3-809e-aaab6382cbe0)
> ![image](https://github.com/3Snake3/Sapphirium/assets/99197260/c09949ef-589b-4dae-8716-f02c860cf8c3)
> Is it intentially?

It is

**Comment by 3Snake3** [comment]
Whirlpool has melee guns, Shriek has huge damage up close, but attacks from the maximum distance

**Comment by Cry0flu1d** [comment]
> > Such as Shriek's main bullet and Whirlpool's side cannon
> > ![image](https://user-images.githubusercontent.com/99197260/269669333-72813e9f-3c63-40f3-809e-aaab6382cbe0.png)
> > ![image](https://user-images.githubusercontent.com/99197260/269670502-c09949ef-589b-4dae-8716-f02c860cf8c3.png)
> > Is it intentially?
> 
> It is

got it
