### ISSUE TITLE
2 things arent working

### ISSUE THREAD

**Issue by DatOnePlayer** [3Snake3/ADC#7]
I cannot play the mod because of 2 stuff
Something involving creotite and the ledonite precipitation, both of them have missing types

**Comment by DatOnePlayer** [comment]
@3Snake3

**Comment by 3Snake3** [comment]
@DatOnePlayer 
Oh... Super Jaba again changed my techtree's code... 
Fixed. You can reinstall the mod

**Comment by DatOnePlayer** [comment]
Thanks!!
